# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakeclaude" do
  name "wakeclaude"
  desc "Schedule Claude Code prompts on macOS."
  homepage "https://github.com/rittikbasu/wakeclaude"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakeclaude"

  on_macos do
    on_intel do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_amd64.tar.gz"
      sha256 "ed2a40535c20166b0f2e441e6783bac14c596dee944bc38dbcc37c491a3a66cb"
    end
    on_arm do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_arm64.tar.gz"
      sha256 "939173f85d3308fb43b9ebe533aa6c0735a5660c113001ad115ce9cd6a4131e7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakeclaude"]
    end
  end

  # No zap stanza required
end
