# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakeclaude" do
  name "wakeclaude"
  desc "Schedule Claude Code prompts on macOS."
  homepage "https://github.com/rittikbasu/wakeclaude"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakeclaude"

  on_macos do
    on_intel do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_amd64.tar.gz"
      sha256 "acff02128ce05c29940b4bbf513e9e38b50c197e267c899e358ef55e01d510f0"
    end
    on_arm do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_arm64.tar.gz"
      sha256 "fcbbc580a2f4711abbe33c8c946aec952585fa97331817f832e07d7b1ec6a5ba"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakeclaude"]
    end
  end

  # No zap stanza required
end
