# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakeclaude" do
  name "wakeclaude"
  desc "Schedule Claude Code prompts on macOS."
  homepage "https://github.com/rittikbasu/wakeclaude"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wakeclaude"

  on_macos do
    on_intel do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_amd64.tar.gz"
      sha256 "a190d63cc0e6c606695f998690de260f9fcf4b26f8ce2c6ed2ad3f13a9af77a8"
    end
    on_arm do
      url "https://github.com/rittikbasu/wakeclaude/releases/download/v#{version}/wakeclaude_#{version}_darwin_arm64.tar.gz"
      sha256 "655817eafcb37cf92ff75e35361bcac35bb5005c0c761a2a55ae36281eb94eab"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wakeclaude"]
    end
  end

  # No zap stanza required
end
